# Generated by Django 4.0.5 on 2022-06-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='members',
        ),
        migrations.AddField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoodapp.hood'),
        ),
    ]
