# Generated by Django 4.0.5 on 2022-06-17 11:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_remove_hood_members_profile_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
