# Generated by Django 4.0.5 on 2022-06-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0008_alter_news_options_alter_business_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('listed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoodapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoodapp.hood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.profile')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoodapp.amenitytype')),
            ],
        ),
    ]
