# Generated by Django 4.0.5 on 2022-06-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoodapp.hood'),
        ),
    ]
