# Generated by Django 4.0.5 on 2022-06-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0011_comment_hood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
