# Generated by Django 4.0.5 on 2022-06-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0014_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
