# Generated by Django 4.0.5 on 2022-06-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0015_remove_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
